/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 20-3-2017 21:30:07 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Adresy_Psc]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Adresy] DROP CONSTRAINT [FK_Adresy_Psc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Destinace_Staty]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Destinace] DROP CONSTRAINT [FK_Destinace_Staty]                                                        
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Fotografie_Hotely]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Fotografie] DROP CONSTRAINT [FK_Fotografie_Hotely]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Hotely_Zpusobystravovani]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Hotely] DROP CONSTRAINT [FK_Hotely_Zpusobystravovani]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Hotely_Destinace]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Hotely] DROP CONSTRAINT [FK_Hotely_Destinace]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Rezervace_Uzivatele]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Rezervace] DROP CONSTRAINT [FK_Rezervace_Uzivatele]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Rezervace_Zajezdy]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Rezervace] DROP CONSTRAINT [FK_Rezervace_Zajezdy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Uzivatele_UzivatelskaPrava]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Uzivatele] DROP CONSTRAINT [FK_Uzivatele_UzivatelskaPrava]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Uzivatele_Adresy]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Uzivatele] DROP CONSTRAINT [FK_Uzivatele_Adresy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Uzivatele_Uzivatelskerole]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Uzivatele] DROP CONSTRAINT [FK_Uzivatele_Uzivatelskerole]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zajezdy_Hotely]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Zajezdy] DROP CONSTRAINT [FK_Zajezdy_Hotely]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Zajezdy_Moznostidopravy]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Zajezdy] DROP CONSTRAINT [FK_Zajezdy_Moznostidopravy]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Adresy]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Adresy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Destinace]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Destinace]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Fotografie]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Fotografie]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Hotely]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Hotely]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Moznostidopravy]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Moznostidopravy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Psc]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Psc]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Rezervace]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Rezervace]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Staty]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Staty]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Uzivatele]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Uzivatele]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UzivatelskaPrava]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UzivatelskaPrava]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Zajezdy]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Zajezdy]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Zpusobystravovani]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Zpusobystravovani]
GO

/* Create Tables */

CREATE TABLE [Adresy]
(
	[Cp] int NOT NULL,
	[Mesto] varchar(40) NOT NULL,
	[Ulice] varchar(40) NOT NULL,
	[AdresyID] int NOT NULL IDENTITY (1, 1),
	[PscID] int NOT NULL
)
GO

CREATE TABLE [Destinace]
(
	[Nazev] varchar(50) NOT NULL,
	[DestinaceID] int NOT NULL IDENTITY (1, 1),
	[StatyID] int NOT NULL
)
GO

CREATE TABLE [Fotografie]
(
	[Fotografie] varchar(MAX) NOT NULL,
	[FotografieID] int NOT NULL IDENTITY (1, 1),
	[HotelyID] int NULL,
	[Popisek] varchar(50) NOT NULL,
	[Nahled] varchar(MAX) NOT NULL
)
GO

CREATE TABLE [Hotely]
(
	[Nazev] varchar(40) NOT NULL,
	[DestinaceID] int NOT NULL,
	[Hodnoceni] int NULL,
	[HotelyID] int NOT NULL IDENTITY (1, 1),
	[email] varchar(50) NOT NULL,
	[ZpusobystravovaniID] int NOT NULL,
	[popis] text NOT NULL
)
GO

CREATE TABLE [Moznostidopravy]
(
	[Typ] varchar(40) NOT NULL,
	[MoznostidopravyID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [Psc]
(
	[Psc] int NOT NULL,
	[PscID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [Rezervace]
(
	[Pocetdospelych] int NOT NULL,
	[Poznámka] text NULL,
	[RezervaceID] int NOT NULL IDENTITY (1, 1),
	[UzivateleID] int NOT NULL,
	[pocetdeti] int NULL,
	[ZajezdyID] int NOT NULL,
	[Zaplaceno] bit NOT NULL
)
GO

CREATE TABLE [Staty]
(
	[Jmeno] varchar(40) NOT NULL,
	[StatyID] int NOT NULL IDENTITY (1, 1)
)
GO

CREATE TABLE [Uzivatele]
(
	[Heslo] varchar(max) NOT NULL,
	[Jmeno] varchar(40) NOT NULL,
	[Login] varchar(40) NOT NULL,
	[Novinky] bit NOT NULL,
	[Prijmeni] varchar(40) NOT NULL,
	[Telefon] varchar(15) NOT NULL,
	[UzivateleID] int NOT NULL IDENTITY (1, 1),
	[AdresyID] int NOT NULL,
	[UzivatelskaPravaID] int NULL
)
GO

CREATE TABLE [UzivatelskaPrava]
(
	[Nazev] varchar(15) NOT NULL,
	[UzivatelskaPravaID] int NOT NULL
)
GO

CREATE TABLE [Zajezdy]
(
	[Cena] money NOT NULL,
	[Do] datetime NOT NULL,
	[Kapacita] int NOT NULL,
	[Od] datetime NOT NULL,
	[ZajezdyID] int NOT NULL IDENTITY (1, 1),
	[HotelyID] int NOT NULL,
	[MoznostidopravyID] int NOT NULL
)
GO

CREATE TABLE [Zpusobystravovani]
(
	[Nazev] varchar(30) NOT NULL,
	[Popis] text NOT NULL,
	[ZpusobystravovaniID] int NOT NULL IDENTITY (1, 1)
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Adresy] 
 ADD CONSTRAINT [PK_Adresy]
	PRIMARY KEY CLUSTERED ([AdresyID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Adresy] 
 ON [Adresy] ([PscID] ASC,[Mesto] ASC,[Ulice] ASC,[Cp] ASC)
GO

ALTER TABLE [Destinace] 
 ADD CONSTRAINT [PK_Destinace]
	PRIMARY KEY CLUSTERED ([DestinaceID] ASC)
GO

ALTER TABLE [Fotografie] 
 ADD CONSTRAINT [PK_Fotografie]
	PRIMARY KEY CLUSTERED ([FotografieID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Fotografie_Hotely_02] 
 ON [Fotografie] ([HotelyID] ASC)
GO

ALTER TABLE [Hotely] 
 ADD CONSTRAINT [PK_Hotely]
	PRIMARY KEY CLUSTERED ([HotelyID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Hotely_Zpusobystravovani] 
 ON [Hotely] ([ZpusobystravovaniID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Hotely] 
 ON [Hotely] ([DestinaceID] ASC,[Hodnoceni] ASC,[Nazev] ASC)
GO

ALTER TABLE [Moznostidopravy] 
 ADD CONSTRAINT [PK_Moznostidopravy]
	PRIMARY KEY CLUSTERED ([MoznostidopravyID] ASC)
GO

ALTER TABLE [Psc] 
 ADD CONSTRAINT [PK_Psc]
	PRIMARY KEY CLUSTERED ([PscID] ASC)
GO

ALTER TABLE [Rezervace] 
 ADD CONSTRAINT [PK_Rezervace]
	PRIMARY KEY CLUSTERED ([RezervaceID] ASC)
GO

ALTER TABLE [Staty] 
 ADD CONSTRAINT [PK_Staty]
	PRIMARY KEY CLUSTERED ([StatyID] ASC)
GO

ALTER TABLE [Uzivatele] 
 ADD CONSTRAINT [PK_Uzivatele]
	PRIMARY KEY CLUSTERED ([UzivateleID] ASC)
GO

ALTER TABLE [Uzivatele] 
 ADD CONSTRAINT [Login] UNIQUE NONCLUSTERED ([Login] ASC)
GO

ALTER TABLE [UzivatelskaPrava] 
 ADD CONSTRAINT [PK_UzivatelskaPrava]
	PRIMARY KEY CLUSTERED ([UzivatelskaPravaID] ASC)
GO

ALTER TABLE [Zajezdy] 
 ADD CONSTRAINT [PK_Zajezdy]
	PRIMARY KEY CLUSTERED ([ZajezdyID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Zajezdy] 
 ON [Zajezdy] ([Od] ASC,[Do] ASC,[Cena] ASC,[HotelyID] ASC)
GO

ALTER TABLE [Zpusobystravovani] 
 ADD CONSTRAINT [PK_Zpusobystravovani]
	PRIMARY KEY CLUSTERED ([ZpusobystravovaniID] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Adresy] ADD CONSTRAINT [FK_Adresy_Psc]
	FOREIGN KEY ([PscID]) REFERENCES [Psc] ([PscID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Destinace] ADD CONSTRAINT [FK_Destinace_Staty]
	FOREIGN KEY ([StatyID]) REFERENCES [Staty] ([StatyID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Fotografie] ADD CONSTRAINT [FK_Fotografie_Hotely]
	FOREIGN KEY ([HotelyID]) REFERENCES [Hotely] ([HotelyID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Hotely] ADD CONSTRAINT [FK_Hotely_Zpusobystravovani]
	FOREIGN KEY ([ZpusobystravovaniID]) REFERENCES [Zpusobystravovani] ([ZpusobystravovaniID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Hotely] ADD CONSTRAINT [FK_Hotely_Destinace]
	FOREIGN KEY ([DestinaceID]) REFERENCES [Destinace] ([DestinaceID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Rezervace] ADD CONSTRAINT [FK_Rezervace_Uzivatele]
	FOREIGN KEY ([UzivateleID]) REFERENCES [Uzivatele] ([UzivateleID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Rezervace] ADD CONSTRAINT [FK_Rezervace_Zajezdy]
	FOREIGN KEY ([ZajezdyID]) REFERENCES [Zajezdy] ([ZajezdyID]) ON DELETE No Action ON UPDATE No Action
GO                      

ALTER TABLE [Uzivatele] ADD CONSTRAINT [FK_Uzivatele_Adresy]
	FOREIGN KEY ([AdresyID]) REFERENCES [Adresy] ([AdresyID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Uzivatele] ADD CONSTRAINT [FK_Uzivatele_Uzivatelskerole]
	FOREIGN KEY ([UzivatelskaPravaID]) REFERENCES  [UzivatelskaPrava]([UzivatelskaPravaID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Zajezdy] ADD CONSTRAINT [FK_Zajezdy_Hotely]
	FOREIGN KEY ([HotelyID]) REFERENCES [Hotely] ([HotelyID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Zajezdy] ADD CONSTRAINT [FK_Zajezdy_Moznostidopravy]
	FOREIGN KEY ([MoznostidopravyID]) REFERENCES [Moznostidopravy] ([MoznostidopravyID]) ON DELETE No Action ON UPDATE No Action
GO
